swagger: '2.0'
info:
  title: API PARTICULIER
  description: |
    ## Bienvenue sur la documentation interactive d'API Particulier.

    Pour utiliser API Particulier en production (particulier.api.gouv.fr), vous devez obtenir un token de production. Pour ce faire, veuillez remplir une [demande d'autorisation](http://signup.api.gouv.fr).

    Pour faire un appel à API Particulier vous devez disposer de deux informations : un token d'API et les informations d'identification d'un particulier.

    Pour les données issues de la DGFIP, les informations d'identification d'un particulier sont : le numéro fiscal et le numéro d'avis d'imposition.

    Pour les données issues de la CAF, les informations d'identification d'un particulier sont : le numéro d'allocataire et le code postal.

    Vous trouverez ci-dessous de quoi exécuter des requêtes HTTP sur l'environnement API Particulier de test (particulier-test.api.gouv.fr). Lors du développement de votre solution logicielle, nous vous recommandons d'utiliser cet environnement.

    ## L'environnement de test

    L'environnement de test est fonctionnellement identique à l'environnement de production.

    Le token d'API à utiliser est un token de test.

    Les données retournées sont des données de test.

    ### Token de test

    Voici la liste des tokens d'API de tests. Chacun donne accès à un *scope* différent.

    | Source | Scope                     | Token                            |
    |--------|---------------------------|----------------------------------|
    | /impots| DGFIP - Avis d'imposition | 83c68bf0b6013c4daf3f8213f7212aa5 |
    | /impots| DGFIP - Adresse           | 02013fe1b5221dd7d914e4406fb88891 |
    | /caf   | CNAF - Quotient familial  | 73af98c480aa3abfd38830ec5c5354d8 |
    | /caf   | CNAF - Attestation droits | 3841b13fa8032ed3c31d160d3437a76a |

     **Important :** la taille du jeu de données retournées dépend du *scope* de la clé d'API utilisée. Certaines clés n'autorisent qu'un nombre réduit de donnée. Ainsi, suivant la clé utilisée, une même requête peut retourner des résultats différents. En effet, les disposition de l'article [L144-8](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000031366350&idArticle=LEGIARTI000031367412&dateTexte=&categorieLien=cid) n'autorise que l'échange des informations **strictement nécessaire** pour traiter une démarche. En conséquence, pendant vos tests, assurez-vous d'utiliser la clé d'API associé au *scope* correspondant aux données auxquelles vous aurez accès d'un point de vue légal.

    ### Informations d'identifications de particulier de test

    Des informations d'identifications de particuliers de test sont disponibles en ligne : [données de la CAF](https://github.com/betagouv/api-particulier/blob/master/api/caf/fake-responses.json) et [données des impôts](https://github.com/betagouv/svair-mock/blob/master/data/seed.csv).

    Si vous souhaitez tester un cas qui n'est pas encore présent, nous vous invitons à faire une demande de modification sur ces fichiers (via une [pull request](https://help.github.com/articles/about-pull-requests/)).

    ## Comment passer de l'environnement de test à l'environnement de production

     Lors de votre passage en production :
     - remplacez l'URL de particulier-test.api.gouv.fr à particulier.api.gouv.fr
     - remplacez la clé d'API de test par la clé d'API obtenue suite à votre [demande d'autorisation](http://signup.api.gouv.fr)

  version: 1.0.0
host: "particulier-test.api.gouv.fr"
basePath: /api
schemes:
- https
produces:
- application/json
paths:
  /impots/svair:
    get:
      summary: Service de vérification de l'avis d'impôt sur le revenu
      description: |
        Le service permet de vérifier l'authenticité du justificatif d'impôt sur
        le revenu ou de l'avis d'impôt sur le revenu présenté par un usager
      parameters:
      - name: numeroFiscal
        in: query
        description: Numéro fiscal propre à chaque citoyen (identifiant numérique de 13 chiffres)
        required: true
        type: number
        format: string
        default: "1702599999001"
      - name: referenceAvis
        in: query
        description: Référence de l'avis fiscal (identifiant numérique de 13 chiffres). Attention, il est possible que l'utilisateur ajoute une quatorzième lettre à la fin de sa référence d'avis. Il s'agit d'une clé de vérification, il est nécessaire de l'enlever avant de l'envoyer sur l'API Particulier.
        required: true
        type: string
        default: "1702599999001"
      - name: X-API-Key
        in: header
        description: Token d'identification de l'API
        required: true
        type: string
        default: 83c68bf0b6013c4daf3f8213f7212aa5
      - name: X-User
        in: header
        description: Utilisateur final de l'API
        required: false
        type: string
        default: "Badul Badul"
      tags:
      - Impots
      responses:
        '200':
          description: A declaration
          schema:
            $ref: '#/definitions/Declaration'
        '401':
          description: Le token ne vous permet pas d'accéder à l'API
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: 'Les paramètres fournis sont incorrects ou ne correspondent pas à un avis'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /caf/famille:
    get:
      summary: Informations concernant la famille
      description: |
        Le service permet de récupérer la composition de la famille, l'adresse déclarée à la CAF, ainsi que le quotient familial.
        Les données sont actualisées chaque mois.
      parameters:
      - name: numeroAllocataire
        in: query
        description: Numéro d'allocataire
        required: true
        type: number
        format: string
        default: "0000354"
      - name: codePostal
        in: query
        description: Code Postal
        required: true
        type: number
        format: string
        default: "99148"
      - name: X-API-Key
        in: header
        description: Token d'identification de l'API
        required: true
        type: string
        default: 3841b13fa8032ed3c31d160d3437a76a
      - name: X-User
        in: header
        description: Utilisateur final de l'API
        required: false
        type: string
        default: "MARIE DUPONT"
      tags:
      - CAF
      responses:
        '200':
          description: Le quotient familial
          schema:
            $ref: '#/definitions/Famille'
        '401':
          description: Le token ne vous permet pas d'accéder à l'API
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: 'Les paramètres fournis sont incorrects ou ne correspondent pas à un allocataire CAF'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /introspect:
    get:
      summary: Introspection du token donné en paramètre
      description: |
        Cet endpoint permet de découvrir les informations correspondant à un token donné
      parameters:
      - name: X-API-Key
        in: header
        description: Token d'identification de l'API
        required: true
        type: string
        default: 83c68bf0b6013c4daf3f8213f7212aa5
      tags:
      - Token
      responses:
        '200':
          description: l'introspection du token
          schema:
            $ref: '#/definitions/Introspection'
        '404':
          description: 'Token not found'
          schema:
            $ref: '#/definitions/Error'
  /ping:
    get:
      summary: Status des serveurs applicatifs API Particulier
      description: |
        Ce endpoint permet de connaitre l'état du serveur API Particulier.
        Si le résultat est autre qu'un code HTTP 200, le serveur rencontre un problème.
        On peut alors considérer que les résultat des autres endpoints seront perturbés.
      tags:
      - Ping
      responses:
        200:
          description: 'pong'
          schema:
            type: string
            example: pong
  /impots/ping:
    get:
      summary: Status des serveurs de la DGFIP
      description: |
        Ce endpoint permet de connaitre l'état du serveur de la DGFIP sur lequel s'appuie API Particulier pour vous restituer les données impôts.
        Si le résultat est autre qu'un code HTTP 200, le serveur de la DGFIP rencontre un problème.
        On peut alors considérer que les résultat du endpoint /impots/svair seront perturbés.
      tags:
      - Ping
      responses:
        '200':
          description: pong
          schema:
            type: string
            example: pong
  /caf/ping:
    get:
      summary: Status des serveurs de la CAF
      description: |
        Ce endpoint permet de connaitre l'état du serveur de la CAF sur lequel s'appuie API Particulier pour vous restituer les données famille.
        Si le résultat est autre qu'un code HTTP 200, le serveur de la CAF rencontre un problème.
        On peut alors considérer que les résultat du endpoint /caf/famille seront perturbés.
      tags:
      - Ping
      responses:
        '200':
          description: pong
          schema:
            type: string
            example: pong

definitions:
  Introspection:
    type: object
    properties:
      _id:
        type: string
        description: Token introspecté
      name:
        type: string
        description: Nom associé au token
      email:
        type: string
        description: email de contact associé au token
  Declaration:
    type: object
    properties:
      declarant1:
        $ref: '#/definitions/Declarant'
      foyerFiscal:
        $ref: '#/definitions/FoyerFiscal'
      declarant2:
        $ref: '#/definitions/Declarant'
      dateRecouvrement:
        type: string
        description: 'Date de recouvrement; format: JJ/MM/AAA'
      dateEtablissement:
        type: string
        description: 'Date d’établissement; format: JJ/MM/AAA'
      nombreParts:
        type: number
        description: 'Nombre de parts'
      situationFamille:
        type: string
        description: Situation familiale (marié, célibataire...)
      nombrePersonnesCharge:
        type: integer
        description: 'Nombre de personne à charge '
      revenuBrutGlobal:
        type: integer
        description: 'Revenu brut global'
      revenuImposable:
        type: integer
        description: 'Revenu imposable'
      impotRevenuNetAvantCorrections:
        type: integer
        description: 'Revenu net avant correction. Prend la valeur null dans le cas d''un revenu non imposable.'
      montantImpot:
        type: integer
        description: 'Total de l’impôt sur le revenu net. Prend la valeur null dans le cas d''un revenu non imposable.'
      revenuFiscalReference:
        type: integer
        description: 'Revenu fiscal de référence'
      anneeImpots:
        type: string
        description: 'Année format: AAAA'
      anneeRevenus:
        type: string
        description: 'Année format: AAAA'
      erreurCorrectif:
        type: string
        description: 'S''il existe un correctif plus récent que l''avis contrôlé, ce champ prend la valeur "Ce document ne correspond pas à la situation la plus récente pour cet usager". Sinon, le champ est absent de la réponse. La présence de ce champ indique qu''il existe un avis d''imposition avec un numéro d''avis distinct qui contient les informations plus récentes. La mise à jour de l''avis initial est en général à l''initiative de l''administré auprès des impôts (par exemple : changement de revenus ou du nombre de part). L''API Particulier peut fournir cet avis à condition de connaître le numéro de l''avis le plus récent. L''API Particulier ne peut pas fournir le numéro de l''avis le plus récent en réponse de l''appel initial. Pour trouver le numéro de cet avis, il faut le demander au particulier auquel l''avis est adressé ou le demander manuellement auprès du centre des impôts de votre région. Vous trouverez de plus amples informations sur <a href="https://www.impots.gouv.fr/portail/precisions-sur-le-service-de-verification-des-avis-dimpot-sur-le-revenu-svair">le site des impôts</a>.'
      situationPartielle:
        type: string
        description: 'Le champ "situationPartielle" indique, dans un foyer marié ou pacsé, le décès d''un des contribuables. Cela signifie qu''il y aura 2 avis de taxations pour une même année : une taxation pour le couple du 01/01/AAAA à la date du décès d''un déclarant, et une autre taxation, pour le conjoint survivant, de la date de décès du conjoint au 31/12/AAAA. Ce champ prend la valeur "(*) Situation  {anneeRevenus}  partielle". Sinon, le champ est absent de la réponse.'

  Declarant:
    type: object
    properties:
      nom:
        type: string
        description: nom du déclarant
      nomNaissance:
        type: string
        description: nom de naissance du déclarant
      prenoms:
        type: string
        description: prenoms du déclarant
      dateNaissance:
        type: string
        description: dateNaissance du déclarant

  FoyerFiscal:
    type: object
    properties:
      annee:
        type: integer
        description: année
      adresse:
        type: string
        description: adresse fiscale de l'année passée

  PosteAdresse:
    type: object
    description: Adresse au format de la poste
    properties:
      identite:
        type: string
        description: '<b>Identité du destinataire : </b>Civilité, titre ou qualité + nom et prénom'
      complementIdentite:
        type: string
        description: "<b>Complément d'information du destinataire ou point de remise : </b>Numéro d'appartement, Escalier"
      complementIdentiteGeo:
        type: string
        description: "<b>Complément d'information du point géographique : </b>Entrée, tour, immeuble, bâtiment, Résidence"
      numeroRue:
        type: string
        description: '<b>Numéro et libellé de la voie</b>'
      lieuDit:
        type: string
        description: '<b>Lieu-dit ou service particulier de distribution :</b> poste restante, boîte postale'
      codePostalVille:
        type: string
        description: '<b>Code postale et localité de destination</b>'
      pays:
        type: string
        description: '<b>Pays</b>'

  Person:
    type: object
    description: Personne référencée à la CAF
    properties:
      nomPrenom:
        type: array
        description: Noms et prénoms des personnes allocataires de la CAF
        items:
          type: string
      dateDeNaissance:
        type: string
        description: "Date de naissance au format: JJMMAAAA"
      sexe:
        type: string
        description: "'M' : masculin ou 'F' : féminin"

  Famille:
    description: Foyer tel qu'il est déclaré à la CAF
    type: object
    properties:
      allocataires:
        type: array
        items:
          $ref: '#/definitions/Person'
      enfants:
        type: array
        items:
          $ref: '#/definitions/Person'
      adresse:
        $ref: '#/definitions/PosteAdresse'
      quotientFamilial:
        type: integer
        description: Valeur du quotient familial calculé par la CAF
      annee:
        type: integer
        description: Année du quotient familial
      mois:
        type: integer
        description: Mois du quotient familial

  Error:
    type: object
    properties:
      reason:
        type: string
      message:
        type: string
      error:
        type: string
