swagger: '2.0'
info:
  title: API Impôt Particulier
  description: >
    ## Bienvenue sur la documentation interactive de l'API Impôt Particulier.


    L'API Impôt Particulier est une API FranceConnectée qui permet de restituer
    des données fiscales relatives à une personne physique utilisant une
    téléservice FranceConnecté.


    Pour utiliser l'API Impôt Particulier en production (xxx.api.gouv.fr), vous
    devez initier une demande de raccordement sur l'espace dédié :
    (https://signup-staging.api.gouv.fr/dgfip).



    Vous trouverez ci-dessous de quoi exécuter des requêtes HTTP sur
    l'environnement API Impôt Particulier de test. Lors du développement de
    votre solution logicielle, nous vous recommandons d'utiliser cet
    environnement.




    ## L'environnement de test Swagger


    Le périmètre des réponses de l'environnement de test est fonctionnellement
    identique à l'environnement de production. Les données retournées sont des
    données fictives.


    Le token d'API à utiliser est un token de test. En production, ce dernier
    est obtenu auprès de FranceConnect lors de la cinématique permettant la
    récupération du consentement de
    l'usager.(https://partenaires.franceconnect.gouv.fr/fcp/fournisseur-service)


    **Important :** Le périmètre de la réponse de l'API dépend du (ou des)
    scope(s) pour le(s)quel(s) l'usager a donné son consentement. Chaque *scope*
    retourne une grappe prédéfinie de données. Ainsi, suivant le *scope*
    utilisé, une même requête peut retourner des résultats différents. En effet,
    les disposition de l'article
    [L144-8](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000031366350&idArticle=LEGIARTI000031367412&dateTexte=&categorieLien=cid)
    n'autorise que l'échange des informations **strictement nécessaires** pour
    traiter une démarche. En conséquence, pendant vos tests, assurez-vous
    d'utiliser les *scopes* correspondants aux données auxquelles vous aurez
    accès d'un point de vue légal.


    ### Données retournées - Scope - Token de test


    Voici la liste des tokens de tests. Chacun d'entre eux donne accès à un
    *scope* différent.

    Les données présentes dans chaque scope, leur nature et leur signification
    fonctionnelle sont décrites plus précisément dans les modèles ci-après.


    | Données                           | Scope             |
    Token                  |

    |-----------------------------------|-------------------|------------------------|

    |Revenu fiscal de référence         | dgfip_rfr
    |83c68bf0b6013c4daf3f8213f7212aa5

    |Nombre de parts fiscales           | dgfip_nbpart
    |02013fe1b5221dd7d914e4406fb88891

    |Adresse fiscale de taxation        | dgfip_aft
    |73af98c480aa3abfd38830ec5c5354d8

    |Situation de famille               | dgfip_sitfam
    |a02506b31c1cd46c2e0b6380fb94eb3d

    |Composition du foyer fiscal        | dgfip_pac
    |2d7428a6b58c40088575f05549f16316

    |Identité des déclarants            | dgfip_decl
    |ddvdxc78p7hhat105zsn5wr0fhymqwzl



    N.B. : En fonction de votre fondement légal et de votre cas d'usage , vous
    pourrez être amené à solliciter plusieurs scopes concomitamment.

    L'interrogation se fait alors en un seul appel et la réponse de l'API
    contiendra l'ensemble des données contenus dans ces scopes.




    ## Environnement de test intégré à l'éco-système FranceConnect


    Un environnement bac à sable est mis à votre disposition avant votre
    raccordement en production à l'API Impôt Particulier.

    Ce mock du FD DGFiP est intégré à l'environnement de pré-production
    FranceConnect.

    Cette intégration vous permet donc de jouer l'ensemble de la cinématique
    FranceConnect depuis l'authentification d'un usager jusqu'à la récupération
    de données auprès du mock FD DGFiP. Vous pouvez l'interroger à l'adresse
    suivante : http://...

    L'ensemble des cas de tests disponibles sur le mock sont disponibles à l'adresse suivante : http://...

    Vous pouvez également installer une instance locale en téléchargeant les
    sources : http://github...


    ### Ajout de cas de tests sur le mock

    Vous utilisez l'outil en ligne : Si vous souhaitez tester des cas métiers
    qui ne sont pas encore présents, nous vous invitons à faire une demande de
    modification sur le fichier database (via une pull request github)


    Vous avez installé une instance locale : Vous pouvez modifier directement le
    fichier database en veillant à générer des identités pivots FranceConnect
    qui soient concordantes avec votre jeu de données.
  version: 1.0.0
host: 'data-provider-example-test.herokuapp.com'
basePath: /
schemes:
- https
produces:
- application/json
paths:
  '/situations/ir/assiettes/annrev/{ANNEE}':
    get:
      summary: Situation IR
      description: >
        Ce endpoint permet d'obtenir des informations relatives à la situation
        fiscale du demandeur.
      parameters:
      - in: path
        name: ANNEE
        required: true
        type: integer
        description: >-
          Année de revenus sollicitée. Les revenus N figurent sur l'avis N+1.
          Pour avoir les revenus de l'avis 2018, je sollicite l'API avec le
          paramètre "AnnRev" 2017
        default: 2017
      - name: Authorization
        in: header
        description: >-
          Il s'agit du token d'accès récupéré auprès de FranceConnect (suite au
          consentement de l'usager) précédé du champ "Bearer:"
        required: true
        type: string
        default: "Bearer: 9af033eb295d0fe113988d29a26527f920114973b3a1ca7bdb44768fd0c73937"
      tags:
      - Impôt sur le revenu (IR)
      responses:
        '200':
          description: Retour OK
          schema:
            $ref: '#/definitions/Declaration'
        '403':
          description: Vous n'avez pas le droit d'accéder à la ressource.

        '404':
          description: "Erreur fonctionnelle : la DGFiP ne retournera pas d'informations liées à cet usager."


definitions:
  Declaration:
    type: object
    properties:
      rfr:
        type: integer
        description: Revenu fiscal de référence
        example: 36705
      sitFam:
        type: string
        enum:
        - M
        - C
        - D
        - V
        - O
        - 'null'
        description: >-
          Situation de famille du foyer fiscal. Il s'agit de la chaîne «null» ou
          d'un caractère qui peut prendre les valeurs suivantes ( M = Marié, C =
          Célibataire, D = Divorcé, V = Veuf, O = Pacsé )
      nbPart:
        type: integer
        minimum: 1
        maximum: 99
        description: Nombre de parts du foyer fiscal
        example: 1
      pac:
        $ref: '#/definitions/PAC'
      nmNaiDec1:
        type: string
        description: Nom de naissance du déclarant 1 de l'avis fiscal
        example: DUPOND
      nmUsaDec1:
        type: string
        description: Nom d'usage du déclarant 1 de l'avis fiscal
        example: null
      prnmDec1:
        type: string
        description: Prénoms du déclarant 1 de l'avis fiscal
        example: JEAN
      nmNaiDec2:
        type: string
        description: 'Nom de naissance du déclarant 2 de l''avis fiscal, null si célibataire'
        example: null
      nmUsaDec2:
        type: string
        description: 'Nom d''usage du déclarant 2 de l''avis fiscal, null si célibataire'
        example: null
      prnmDec2:
        type: string
        description: 'Prénoms du déclarant 2 de l''avis fiscal, null si célibataire'
        example: null
      aft:
        type: string
        description: Adresse fiscale de taxation de l'usager
        example: BAT 3 APT 93 10 RUE DU CENTRE 93160 NOISY LE GRAND
      aftDetail:
        $ref: '#/definitions/AFT'
  PAC:
    type: object
    properties:
      nbPac:
        type: integer
        description: nombre total de personnes à charge dans le foyer
      nbPacF:
        type: integer
        description: nombre d'enfants mineurs à la charge exclusive du foyer
      nbPacH:
        type: integer
        description: >-
          nombre d'enfants mineurs en résidence alternée (divorce, séparation
          ...)
      nbPacR:
        type: integer
        description: nombre de personnes invalides à charge
      nbPacJ:
        type: integer
        description: nombre d'enfants majeurs à charge et célibataires
      nbPacN:
        type: integer
        description: >-
          nombre d'enfants majeurs mariés/pacsés avec ou sans charge de famille
          et d'enfants non mariés/pacsés chargés de famille
      nbPacP:
        type: integer
        description: nombre de petits-enfants en résidence alternée
  AFT:
    type: object
    properties:
      complementAdresse:
        type: string
        description: >-
          indications complémentaires éventuelles (Batiment, Escalier,
          Appartement... ), null si non utilisé
        example: BAT 3 APT 93
      voie:
        type: string
        description: numéro + type de voie + nom de la voie
        example: 10 RUE DU CENTRE
      commune:
        type: string
        description: 'bureau postal distributeur au besoin, null sinon'
        example: null
      codePostal:
        type: string
        description: code postal sur 5 chiffres + ville de résidence de l'usager
        example: 93160 NOISY LE GRAND
  Error:
    type: object
    properties:
      reason:
        type: string
      message:
        type: string
      error:
        type: string
