swagger: '2.0'
info:
  title: API Impôt Particulier
  description: >
    # Bienvenue sur la documentation interactive de l'API Impôt Particulier.


    L'API Impôt Particulier est une API qui permet de restituer des données
    fiscales relative à une personne physique utilisant une téléservice
    FranceConnecté.

    Pour utiliser l'API Impôt Particulier en production, vous devez initier une
    demande de raccordement sur l'espace dédié : (http://signup.api.gouv.fr).


    ## L'appel de l'API impôt particulier


    Le token d'API à utiliser est un token de test. En production, ce dernier
    est obtenu auprès de FranceConnect lors de la cinématique permettant la
    récupération du consentement de
    l'usager.(https://partenaires.franceconnect.gouv.fr/fcp/fournisseur-service)


    **Important :** Le périmètre de la réponse de l'API dépend du (ou des)
    scope(s) pour le(s)quel(s) l'usager a donné son consentement. Chaque *scope*
    retourne une grappe prédéfinie de données. Ainsi, suivant le *scope*
    utilisé, une même requête peut retourner des résultats différents. En effet,
    les disposition de l'article
    [L144-8](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000031366350&idArticle=LEGIARTI000031367412&dateTexte=&categorieLien=cid)
    n'autorise que l'échange des informations **strictement nécessaire** pour
    traiter une démarche. En conséquence, pendant vos tests, assurez-vous
    d'utiliser les *scopes* correspondants aux données auxquelles vous aurez
    accès d'un point de vue légal.


    ## Données retournées - Scope - Token de test


    Voici la liste des tokens de tests. Chacun d'entre eux donne accès à un
    *scope* différent.

    Les données présentes dans chaque scope, leur nature et leur signification
    fonctionnelle sont décrites plus précisément dans les modèles ci-après.  


    | Données                           | Scope             |
    Token                  |

    |-----------------------------------|-------------------|------------------------|

    |Revenu fiscal de référence         | dgfip_rfr        
    |83c68bf0b6013c4daf3f8213f7212aa5 

    |Nombre de parts fiscales           | dgfip_nbpart     
    |02013fe1b5221dd7d914e4406fb88891

    |Adresse fiscale de taxation        | dgfip_aft        
    |73af98c480aa3abfd38830ec5c5354d8 

    |Données du local                   | dgfip_locaux_th  
    |a02506b31c1cd46c2e0b6380fb94eb3d

    |


    N.B. : En fonction de votre fondement légal et de votre cas , vous pourrez
    être amené à solliciter plusieurs scopes concomitamment. 

     ## L'environnement de tests proposé par la DGFiP
    Une fois votre demande de souscription pré-validée par la DGFiP, vous pouvez
    accéder à un environnement test.


    Le périmètre des réponses de  cet environnement de test est
    fonctionnellement identique à l'environnement de production. 


    Un jeu de données fictives avec plusieurs cas nominaux vous permet de valider
    l'intégration de quelques cas fonctionnels dans votre téléservice.
    L'environnement de test proposé par la DGFiP n'a donc pas vocation à recetter toutes
    les fonctionnalités du téléservice, qui doivent faire l'objet d'une recette
    interne


    Lors du développement de votre solution logicielle, nous vous recommandons
    d'utiliser cet environnement.


      
    ### Jeu de données fictifs


    Des données complémentaires de test sont disponibles en ligne :
    https://github.com/betagouv/svair-mock/blob/master/data/seed.csv


    Si vous souhaitez tester un cas qui n'est pas encore présent, nous vous
    invitons à faire une demande de modification sur ces fichiers (via une [pull
    request](https://help.github.com/articles/about-pull-requests/)).


    ## Environnement de test intégré à l'éco-système FranceConnect


    [À venir...]
    
  version: 1.0.0
host: 'localhost:3000'
basePath: /
schemes:
  - https
produces:
  - application/json
paths:
  '/situations/ir/assiettes/annrev/{ANNEE}':
    get:
      summary: Situation IR
      description: >
        Ce endpoint permet d'obtenir des informations relatives à la situation
        fiscale du demandeur. 
      parameters:
        - in: path
          name: ANNEE
          required: true
          type: integer
          description: >-
            Année de revenus sollicitée. Les revenus N figurent sur l'avis N+1.
            Pour avoir les revenus de l'avis 2018, je sollicite l'API avec le
            paramètre "AnnRev" 2017
          default: 2017
        - name: Bearer
          in: header
          description: >-
            Il s'agit du token d'accès récupéré auprès de FranceConnect suite au
            consentement de l'usager
          required: true
          type: string
          default: 83c68bf0b6013c4daf3f8213f7212aa5
      tags:
        - Impôt sur le revenu (IR)
      responses:
        '200':
          description: Retour OK
          schema:
            $ref: '#/definitions/Declaration'
        '401':
          description: Le token ne vous permet pas d'accéder à l'API
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: >-
            Les paramètres fournis sont incorrects ou ne correspondent pas à un
            avis
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Declaration:
    type: object
    properties:
      rfr:
        type: integer
        description: Revenu fiscal de référence
        example: 36705
      nbPart:
        type: integer
        minimum: 1
        maximum: 99
        description: Nombre de parts du foyer fiscal
        example: 1
      aft:
        type: string
        description: Adresse fiscale de taxation de l'usager
        example: BAT 3 APT 93 10 RUE DU CENTRE 93160 NOISY LE GRAND
      aftDetail:
        $ref: '#/definitions/AFT'
      Donnéeslocal:
        $ref: '#/definitions/LOCAL'
  AFT:
    type: object
    properties:
      complementAdresse:
        type: string
        description: >-
          indications complémentaires éventuelles (Batiment, Escalier,
          Appartement... ), null si non utilisé
        example: BAT 3 APT 93
      voie:
        type: string
        description: numéro + type de voie + nom de la voie
        example: 10 RUE DU CENTRE
      commune:
        type: string
        description: 'bureau postal distributeur au besoin, null sinon'
        example: null
      codePostal:
        type: string
        description: code postal sur 5 chiffres + ville de résidence de l'usager
        example: 93160 NOISY LE GRAND
  LOCAL:
    type: object
    properties:
      regimeTax:
        type: string
        description: >-
          Régime de taxation (code sur un caractère) P = principal. L'API ne
          retourne que les données du local de l'habitation principale
        example: P
      locaux.natureLocal:
        type: string
        description: type de bien (code sur deux caractères)
        example: 'MA, ME, MP, AP'
      locauxaffectation:
        type: string
        description: >-
          Type d'affectation (code sur une lettre).L'API ne retourne que les
          locaux avec une affectation "H" pour habitation.
        example: H
      locauxinvariant:
        type: string
        description: identifiant du local
        example: null
  Error:
    type: object
    properties:
      reason:
        type: string
      message:
        type: string
      error:
        type: string
